#database configuration
spring:
  datasource:
    password: sasa
    url: jdbc:postgresql://localhost:5432/examdb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    show-sql: true
server:
  port : 8082
jwt:
  secret: examportal